import {
  SiGithub,
  SiLinkedin,
  SiX,
  SiInstagram,
  SiFacebook,
  SiYoutube,
  SiTiktok,
  SiReddit,
  SiDevdotto,
  SiMedium,
  SiStackoverflow,
  SiLeetcode,
  SiDribbble,
  SiBehance,
  SiHackerrank,
  SiCodepen,
  SiCodesandbox,
  SiGitlab,
  SiBitbucket,
  SiKaggle,
  SiSnapchat,
  SiDiscord,
  SiReplit,
  SiNotion,
  SiSubstack,
} from 'react-icons/si';

import { IconType } from 'react-icons';

export const socialIconMap: Record<string, IconType> = {
  github: SiGithub,
  linkedin: SiLinkedin,
  x: SiX,
  instagram: SiInstagram,
  facebook: SiFacebook,
  youtube: SiYoutube,
  tiktok: SiTiktok,
  reddit: SiReddit,
  devto: SiDevdotto,
  medium: SiMedium,
  stackoverflow: SiStackoverflow,
  leetcode: SiLeetcode,
  dribbble: SiDribbble,
  behance: SiBehance,
  hackerrank: SiHackerrank,
  codepen: SiCodepen,
  codesandbox: SiCodesandbox,
  gitlab: SiGitlab,
  bitbucket: SiBitbucket,
  kaggle: SiKaggle,
  snapchat: SiSnapchat,
  discord: SiDiscord,
  replit: SiReplit,
  notion: SiNotion,
  substack: SiSubstack,
};
